name: Release Flow

on:
  workflow_dispatch:

env:
  APP_NAME: app
  REGISTRY_HOST: cr.yandex
  REESTR_ID: ${{ secrets.REESTR_ID }}

jobs:
  # 1. Проверки (lint + test)
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm run test

  # 2. Сборка и пуш Docker образа
  build-and-push:
    needs: lint-test
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_IAM_TOKEN }}" | docker login --username oauth --password-stdin ${{ env.REGISTRY_HOST }}

      - name: Build and tag Docker image
        run: |
          docker build \
            -t ${{ env.REGISTRY_HOST }}/${{ env.REESTR_ID }}/${{ env.APP_NAME }}:${{ env.VERSION }} \
            -t ${{ env.REGISTRY_HOST }}/${{ env.REESTR_ID }}/${{ env.APP_NAME }}:${{ env.VERSION }}_latest \
            .

      - name: Push Docker images
        run: |
          docker push ${{ env.REGISTRY_HOST }}/${{ env.REESTR_ID }}/${{ env.APP_NAME }}:${{ env.VERSION }}
          docker push ${{ env.REGISTRY_HOST }}/${{ env.REESTR_ID }}/${{ env.APP_NAME }}:${{ env.VERSION }}_latest

  # 3. Создание релизной ветки
  release-branch:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
      - name: Create release branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b releases/${{ env.VERSION }}
          git push origin releases/${{ env.VERSION }}

  # 4. Создание тега и обновление CHANGELOG.md
  tag-and-changelog:
    needs: release-branch
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: releases/${{ env.VERSION }}
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --tags
      - name: Create git tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
      - name: Generate changelog entry
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 ${{ env.VERSION }}^ 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            RANGE="${PREV_TAG}..HEAD"
          else
            RANGE="HEAD"
          fi
          COMMITS=$(git log $RANGE --pretty=format:'- %s (%an)')
          DATE=$(date -u +"%Y-%m-%d")
          echo -e "## ${{ env.VERSION }} ($DATE)\n\n$COMMITS\n" > new_changelog.md
      - name: Prepend new changelog to CHANGELOG.md
        run: |
          cat new_changelog.md CHANGELOG.md > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
      - name: Commit updated CHANGELOG.md
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for release ${{ env.VERSION }}"
          git push origin releases/${{ env.VERSION }}

  # 5. GitHub Issue с информацией о релизе
  create-issue:
    needs: tag-and-changelog
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.run_number }}
      APP_NAME: ${{ env.APP_NAME }}
      REGISTRY_HOST: ${{ env.REGISTRY_HOST }}
      REESTR_ID: ${{ env.REESTR_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare issue content
        run: |
          REG="${REGISTRY_HOST}/${REESTR_ID}"
          DATE=$(date -u +"%Y-%m-%d")
          PREV_TAG=$(git describe --tags --abbrev=0 $VERSION^ 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            LOG=$(git log $PREV_TAG..HEAD --pretty=format:'- %s (%an)')
          else
            LOG=$(git log --pretty=format:'- %s (%an)')
          fi

          cat <<EOF > .github/release-issue.md
          **Release**: $VERSION
          **Date**: $DATE UTC
          **Author**: @${{ github.actor }}

          **Commits:**
          $LOG

          **Docker images:**
          - \`$REG/$APP_NAME:$VERSION\`
          - \`$REG/$APP_NAME:${VERSION}_latest\`
          EOF

      - name: Create GitHub Issue
        uses: actions/github-script@v7
        env:
          VERSION: ${{ env.VERSION }}
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('.github/release-issue.md', 'utf8');

            const result = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Release v${process.env.VERSION}`,
              body: content
            });

            core.setOutput("issue_number", result.data.number);
